import { UserId, NotificationCreatedEvent } from '@packages/domain';
import { UserRepository } from '@packages/persistence';
import { logger } from '../../config/logger.config';
import type { AddNotificationRequest } from '@packages/contracts';
import { eventBus } from '../../infrastructure/events';

/**
 * Use Case: Add Notification to User
 * 
 * Responsabilidades:
 * 1. Validar formato de userId
 * 2. Delegar creación de notificación al repositorio
 * 3. Log de errores sin bloquear operación principal
 * 
 * Patrón de uso:
 * - Este use case es INTERNO, llamado por otros features (QuickCheck, Events, Maintenance)
 * - Fire-and-forget: errores se loggean pero no se propagan
 * - No expuesto en REST API directamente
 * 
 * Sprint #9 - Sistema de Notificaciones
 */
export class AddNotificationUseCase {
  private userRepository: UserRepository;

  constructor() {
    this.userRepository = new UserRepository();
  }

  /**
   * Ejecuta el caso de uso de agregar notificación
   * 
   * @param userId - ID del usuario que recibirá la notificación
   * @param notification - Datos de la notificación (type, message, actionUrl, sourceType)
   * @returns Promise<void> - Fire-and-forget, errores se loggean internamente
   */
  async execute(
    userId: string,
    notification: AddNotificationRequest
  ): Promise<void> {
    try {
      // 1. Validar formato de userId
      const userIdResult = UserId.create(userId);
      if (!userIdResult.success) {
        logger.error({ 
          userId, 
          error: userIdResult.error.message 
        }, 'Invalid userId format when adding notification');
        return; // Silent fail - no bloquear operación principal
      }

      // 2. Agregar notificación usando repositorio
      const addResult = await this.userRepository.addNotification(
        userIdResult.data,
        {
          notificationType: notification.notificationType,
          message: notification.message,
          actionUrl: notification.actionUrl,
          sourceType: notification.sourceType,
          metadata: notification.metadata
        }
      );

      if (!addResult.success) {
        logger.error({ 
          userId,
          error: addResult.error.message,
          notificationType: notification.notificationType
        }, 'Failed to add notification');
        return; // Silent fail
      }

      logger.info({ 
        userId,
        notificationType: notification.notificationType,
        sourceType: notification.sourceType
      }, 'Notification added successfully');

      // 3. Emit domain event for real-time push via SSE
      // EventBus → SSEManager → Push to all connected devices
      // 
      // Note: addNotification returns Result<void>, so we construct event from input data.
      // The notification ID is generated by MongoDB (subdocument _id), but we don't need it
      // for the real-time push - frontend will refetch full notification list.
      try {
        eventBus.emit('notification-created', new NotificationCreatedEvent(
          userId,
          'generated_by_db', // MongoDB generates subdocument _id - not critical for SSE
          notification.notificationType,
          notification.message,
          new Date(), // Current timestamp (matches DB notificationDate)
          notification.actionUrl,
          notification.sourceType,
          notification.metadata
        ));

        logger.debug({
          userId,
          notificationType: notification.notificationType,
          sourceType: notification.sourceType
        }, 'Domain event emitted: notification-created');
      } catch (eventError) {
        // Event emission failure shouldn't break notification creation
        // SSE is nice-to-have, DB persistence is critical
        const errorMessage = eventError instanceof Error ? eventError.message : 'Unknown error';
        logger.error({
          userId,
          error: errorMessage
        }, 'Failed to emit notification-created event (SSE push failed)');
      }

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      logger.error({ 
        userId,
        error: errorMessage,
        notificationType: notification.notificationType
      }, 'Unexpected error adding notification');
      // No re-throw - fire-and-forget pattern
    }
  }
}
